# Header
menu:
  主页: /
  标签: /tags
  归档: /archives

# SubNav
subnav:
  github: "https://github.com/gary-Shen"
  weibo: "http://weibo.com/grinson"
  #rss: "#"
  #zhihu: "#"
  #douban: "#"
  #mail: "grinson50@gmail.com"
  facebook: "https://www.facebook.com/profile.php?id=100003104963576"
  #google: "#"
  twitter: "https://twitter.com/grinson50"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: 阅读全部
fancybox: true
mathjax: false

#主题方案
highlight_theme: night eighties

# Miscellaneous
google_analytics: 'UA-61220413-1'

#站点favicon图标
favicon: /img/favicon.png

#你的头像url
avatar: "/img/profile.jpg"
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: garyfed
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
friends: false
#开启——
#friends:
#  奥巴马的博客: http://localhost:4000/
#  卡卡的美丽传说: http://localhost:4000/
#  本泽马的博客: http://localhost:4000/
#  吉格斯的博客: http://localhost:4000/
#  习大大大不同: http://localhost:4000/
#  托蒂的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
#aboutme: true
#开启——
aboutme: 关注UX，FD，专注Web前端开发，用余生探索未知。
